steps:
  - id: Build
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/retf:$SHORT_SHA
      - --cache=true
      - --cache-ttl=24h

  - id: Test
    name: gcr.io/$PROJECT_ID/retf:$SHORT_SHA
    dir: /app
    args:
      - ci

  - name: gcr.io/cloud-builders/gcloud
    id: Generate
    entrypoint: /bin/bash
    args:
      - cloudbuild/deploy.sh
    env:
      - PROJECT_ID=$PROJECT_ID
      - SHORT_SHA=$SHORT_SHA

  - name: gcr.io/cloud-builders/kubectl
    id: Deploy
    args:
      - apply
      - -f
      - kubernetes.yaml
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-west1-a
      - CLOUDSDK_CONTAINER_CLUSTER=nnyc
