steps:
  - id: Test
    name: "node:12"
    entrypoint: /bin/sh
    args:
      - -c
      - yarn install; yarn run compile:ci; yarn run test; yarn run lint:ci

  - id: Build
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/retf-app:$SHORT_SHA
      - .

  - id: Push
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/retf-app:$SHORT_SHA

  - name: "gcr.io/cloud-builders/gcloud"
    id: Decrypt SSH key
    args:
      - kms
      - decrypt
      - --key=projects/airy-charge-246717/locations/global/keyRings/falcor/cryptoKeys/github-deploy
      - --ciphertext-file=cloudbuild/id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/gcloud"
    id: Clone env repo
    entrypoint: /bin/bash
    args:
      - -c
      - cloudbuild/clone.sh
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/gcloud"
    id: Update manifest
    entrypoint: /bin/bash
    args:
      - -c
      - cloudbuild/gen_kube.sh

  - name: "gcr.io/cloud-builders/gcloud"
    id: Push manifest
    entrypoint: /bin/sh
    args:
      - cloudbuild/push_kube.sh
    volumes:
      - name: "ssh"
        path: /root/.ssh
