steps:
  - id: Test
    name: "node:12"
    entrypoint: /bin/sh
    args:
      - -c
      - yarn install; yarn run compile:ci; yarn run test; yarn run lint:ci

  - id: Build
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/retf-app:$SHORT_SHA
      - .

  - id: Push
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/retf-app:$SHORT_SHA

  - name: "gcr.io/cloud-builders/gcloud"
    id: Decrypt SSH key
    args:
      - kms
      - decrypt
      - --key=projects/airy-charge-246717/locations/global/keyRings/falcor/cryptoKeys/github-deploy
      - --ciphertext-file=cloudbuild/id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    id: Configure SSH
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod 600 /root/.ssh/id_rsa
        cat << EOF > /root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv cloudbuild/known_hosts /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/gcloud"
    id: Clone env repo
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        git clone git@github.com:mplewis/retf-env.git && \
        cd retf-env && \
        git checkout candidate && \
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
        ls -la .
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/gcloud"
    id: Update manifest
    entrypoint: /bin/bash
    args:
      - cloudbuild/gen_kube.sh

  - name: "gcr.io/cloud-builders/gcloud"
    id: Push manifest
    entrypoint: /bin/sh
    args:
      - cloudbuild/push_kube.sh
