steps:
  - id: Build and push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/retf-app:$SHORT_SHA
      - --cache=true
      - --cache-ttl=24h

  - id: Test
    name: gcr.io/$PROJECT_ID/retf-app:$SHORT_SHA
    dir: /app
    args:
      - ci

  - name: gcr.io/cloud-builders/gcloud
    id: Deploy
    entrypoint: /bin/bash
    args:
      - cloudbuild/deploy.sh
    env:
      - PROJECT_ID=$PROJECT_ID
      - SHORT_SHA=$SHORT_SHA
