version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run: yarn compile
      - run: rm -rf dist
      - run: yarn test:ci
      - run: yarn lint:ci
