version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - docker/publish:
          image: mplewis/discosay
          tag: latest,<< pipeline.git.tag >>
          update-description: true
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - docker/build:
          image: mplewis/cowman
          lint: true
